micronaut.application.name=caloriesCounter

liquibase.enabled=true
liquibase.datasources.default.change-log=db/changelog/db.changelog-master.yaml

datasources.default.db-type=h2
datasources.default.dialect=H2
datasources.default.url=${H2_URL}
datasources.default.username=${H2_USERNAME}
datasources.default.password=${H2_PASSWORD}